stages:
  download:
    cmd: python src/download.py
    params:
    - download.n_locs
    - download.year
  prepare:
    cmd: python src/prepare.py data/downloaded
    deps:
    - data/downloaded
    - src/prepare.py
    outs:
    - data/prepared
  process:
    cmd: python src/process.py data/downloaded
    deps:
    - data/downloaded
    - src/process.py
    outs:
    - data/processed
  evaluate:
    cmd: python src/evaluate.py data/prepared/ground_truth.txt data/processed/computed_monthly_averages.txt
    deps:
    - data/prepared
    - data/processed
    - src/evaluate.py
    outs:
    - data/evaluated
